
substitutions:
  NODE: "Dev Screen"
  TEXT_TITLE: "CatsLair"
  FONT_SIZE_CLOCK: "48"
  FONT_SIZE_ICONS: "44"
  FONT_SIZE_BIG: "26"
  FONT_SIZE_TINY: "14"
  <<: !include includes/fonts_subs.yaml

<<: !include includes/common_network.yaml

packages:
  ha: !include packages/ha_sensors.yaml
  internal: !include packages/internal_sensors.yaml
  fonts: !include packages/fonts.yaml
  dimmer: !include packages/auto_dim.yaml

esphome:
  name: screen2
  includes:
  - includes/display_functions.h
  - includes/auto_dim.h
  on_boot:
    then:
      - lambda: |-
           uint8_t val = 0x40;
           uint8_t len = 1;
           my_display->send_command(esphome::ili9xxx::ILI9XXX_MADCTL, &val, len);

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO

globals:
   - id: page
     type: int
     initial_value: "1"
   
spi: 
   - clk_pin: GPIO14
     mosi_pin: GPIO13
     miso_pin: GPIO12
     id: bus_tft

   - clk_pin: GPIO25
     mosi_pin: GPIO32
     miso_pin: GPIO39
     id: bus_ts

i2c:
   - sda: GPIO27
     scl: GPIO22
     scan: true
     id: bus_a

touchscreen:
  platform: xpt2046
  interrupt_pin: 36
  cs_pin: 33
  display: my_display
  id: my_touchscreen
  spi_id: bus_ts
  update_interval: 50ms
  threshold: 400
  calibration_x_min: 3775
  calibration_x_max: 404
  calibration_y_min: 3587
  calibration_y_max: 289
  transform:
    swap_xy: true
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );

output:
# Internal LED
  - platform: ledc
    pin: GPIO21
    id: backlight_pin

# Other LEDs
  - platform: ledc
    id: output_red
    pin: GPIO4
    inverted: true

  - platform: ledc
    id: output_green
    pin: GPIO16
    inverted: true

  - platform: ledc
    id: output_blue
    pin: GPIO17
    inverted: true


light:
  - platform: monochromatic
    output: backlight_pin
    name: "${NODE} Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

  - platform: rgb
    name: LED
    id: led
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - strobe:
          name: "Strobe"
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms

sensor:

  - platform: adc
    pin: 34
    name: "${NODE} Light Level"
    id: internal_ldr
    update_interval: 5s
    on_value:
      - lambda: change_adc(1.08-x);


binary_sensor:

  - platform: touchscreen
    id: bottom_A
    name: "${NODE} Touch A"
    x_min: 1
    x_max: 80
    y_min: 200
    y_max: 339
    on_press:
      - lambda: id(page) = 1;
       

  - platform: touchscreen
    id: bottom_B
    name: "${NODE} Touch B"
    x_min: 80 
    x_max: 160
    y_min: 200
    y_max: 339 
    on_press:
      - lambda: id(page) = 2;

  - platform: touchscreen
    id: bottom_C
    name: "${NODE} Touch C"
    x_min: 160
    x_max: 240
    y_min: 200
    y_max: 339
    on_press:
      - lambda: id(page) = 3;

display:
  - platform: ili9xxx
    id: my_display
    spi_id: bus_tft
    rotation: 90
    dc_pin: GPIO2
    cs_pin: GPIO15
    model: TFT_2.4R
    data_rate: 40MHz
    <<: !include includes/display_lambda.yaml
