
substitutions:
  NODE: "Kitchen Display"
  TEXT_TITLE: "CatsLair"
  FONT_SIZE_CLOCK: "52"
  FONT_SIZE_BIG: "30"
  FONT_SIZE_ICONS: "60"
  <<: !include packages/fonts_subs.yaml


packages:
  ha: github://jaredquinn/esphome-wx/packages/ha_sensors_mini.yaml
  internal: github://jaredquinn/esphome-wx/packages/internal_sensors.yaml
  fonts: github://jaredquinn/esphome-wx/packages/fonts.yaml

esphome:
  name: screenkitchen

# This device is a ESP32-C3 RISC-V based MCU.
esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

# See README.md the components directory, this is a modified version
# of a previous ESPhome PR
external_components:
  - source: components
    components: ["gc9a01"]

<<: !include common_network.yaml

logger:
  level: DEBUG

# Touchscreen is on an I2C device, supporting coming soon?!?
i2c:
 - sda: GPIO4
   scl: GPIO5
   scan: true
   id: bus_a


spi:
  mosi_pin: GPIO7
  miso_pin: GPIO2
  clk_pin: GPIO6

output:
  - platform: ledc
    pin: GPIO3
    id: backlight_pin

light:
  - platform: monochromatic
    output: backlight_pin
    name: "${NODE} Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

# Touchscreen support is a work in progress on this device
# See the readme for more information

#touchscreen:
#  platform: cst816s
#  interrupt_pin: GPIO0
#  reset_pin: GPIO1


display:
- platform: gc9a01
  cs_pin: GPIO10
  dc_pin: GPIO2
  rotation: 90
  update_interval: 50ms
  <<: !include includes/display_lambda_mini.yaml
