
substitutions:
  NODE: "DIY Display"
  TEXT_TITLE: "CatsLair"
  FONT_SIZE_CLOCK: "48"
  FONT_SIZE_ICONS: "44"
  FONT_SIZE_BIG: "26"
  FONT_SIZE_TINY: "14"
  <<: !include packages/fonts_subs.yaml

spi: 
   - clk_pin: GPIO18
     mosi_pin: GPIO23
     miso_pin: GPIO19
     id: bus_tft

   - clk_pin: GPIO14
     mosi_pin: GPIO13
     miso_pin: GPIO12
     id: bus_ts

packages:
  ha: github://jaredquinn/esphome-wx/packages/ha_sensors.yaml
  internal: github://jaredquinn/esphome-wx/packages/internal_sensors.yaml
  fonts: github://jaredquinn/esphome-wx/packages/fonts.yaml

output:
  - platform: gpio
    pin: GPIO16
    id: gpio_16

light:
  - platform: binary
    output: gpio_16
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON


display:
  - platform: ili9xxx
    id: my_display
    spi_id: bus_tft
    reset_pin: GPIO25
    dc_pin: GPIO26
    cs_pin: GPIO27
    model: ili9341
    data_rate: 80MHz
    <<: !include includes/display_lambda.yaml

