
switch:
  - platform: restart
    name: "${NODE} ESP32 Restart"

sensor:
  - platform: uptime
    id: up
    name: "${NODE} System Uptime"
    internal: true
    update_interval: 60s

  - platform: wifi_signal
    name: "${NODE} WiFi Signal"
    id: wifi_db
    update_interval: 60s


text_sensor:
  - platform: wifi_info
    ip_address:
       id: wifi_ipaddress
       name: "${NODE} WiFi IP Address"
    ssid:
       id: wifi_ssid
       name: "${NODE} WiFi SSID"
    mac_address:
       id: wifi_mac
       name: "${NODE} WiFi MAC"

#  - platform: homeassistant
#    name: "OpenWeather"
#    id: forecast
#    entity_id: sensor.forecast_2
 
binary_sensor:

  - platform: status
    name: "${NODE} Node Status"
    id: system_status

